"""update share post

Revision ID: 1e9db022059b
Revises: 64a3174e64bf
Create Date: 2024-05-28 14:48:46.101449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9db022059b'
down_revision = '64a3174e64bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_post', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_share', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('count_share')
        batch_op.drop_column('type_post')

    # ### end Alembic commands ###
