"""update count notification

Revision ID: 64a3174e64bf
Revises: 7b9204affac7
Create Date: 2024-05-12 21:22:17.300697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a3174e64bf'
down_revision = '7b9204affac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_notification', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('count_notification')

    # ### end Alembic commands ###
