"""update room chat in friend

Revision ID: 7b9204affac7
Revises: d18e2bd02014
Create Date: 2024-04-13 13:01:46.304984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9204affac7'
down_revision = 'd18e2bd02014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_room_chat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_column('id_room_chat')

    # ### end Alembic commands ###
