"""update table friend

Revision ID: fecc739ea2d9
Revises: 6c0b5b6fdd62
Create Date: 2024-03-19 13:20:50.817801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecc739ea2d9'
down_revision = '6c0b5b6fdd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_like', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_comment', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('count_comment')
        batch_op.drop_column('count_like')

    # ### end Alembic commands ###
